import type { ChecklistItem } from "@shared/schema";

export const defaultChecklistItems: ChecklistItem[] = [
  // SMB Enumeration
  {
    id: "smb-enum-1",
    serviceType: "smb",
    category: "enumeration",
    title: "Enumerate shares with smbclient",
    description: "List available SMB shares anonymously",
    command: "smbclient -N -L //$target_ip",
    order: 1,
  },
  {
    id: "smb-enum-2",
    serviceType: "smb",
    category: "enumeration",
    title: "Enumerate shares with NetExec",
    description: "Use NetExec for quick SMB enumeration",
    command: "nxc smb $target_ip --shares",
    order: 2,
  },
  {
    id: "smb-enum-3",
    serviceType: "smb",
    category: "enumeration",
    title: "Enumerate users with enum4linux",
    description: "Run enum4linux for comprehensive SMB enumeration",
    command: "enum4linux -a $target_ip",
    order: 3,
  },
  {
    id: "smb-enum-4",
    serviceType: "smb",
    category: "enumeration",
    title: "Check for null session",
    description: "Test if null session is allowed",
    command: "smbclient //$target_ip/IPC$ -N",
    order: 4,
  },
  {
    id: "smb-enum-5",
    serviceType: "smb",
    category: "enumeration",
    title: "RID cycling for usernames",
    description: "Enumerate users via RID cycling",
    command: "nxc smb $target_ip --rid-brute",
    order: 5,
  },
  {
    id: "smb-unauth-1",
    serviceType: "smb",
    category: "unauthenticated",
    title: "Check for EternalBlue (MS17-010)",
    description: "Scan for MS17-010 vulnerability",
    command: "nmap --script smb-vuln-ms17-010 -p445 $target_ip",
    links: ["https://www.rapid7.com/db/modules/exploit/windows/smb/ms17_010_eternalblue"],
    order: 10,
  },
  {
    id: "smb-unauth-2",
    serviceType: "smb",
    category: "unauthenticated",
    title: "Check for SMB signing",
    description: "Verify if SMB signing is required (relay attacks)",
    command: "nxc smb $target_ip --gen-relay-list relay.txt",
    order: 11,
  },
  {
    id: "smb-auth-1",
    serviceType: "smb",
    category: "authenticated",
    title: "Access shares with credentials",
    description: "Connect to shares with valid credentials",
    command: "smbclient //$target_ip/share -U 'username%password'",
    order: 20,
  },
  {
    id: "smb-auth-2",
    serviceType: "smb",
    category: "authenticated",
    title: "Enumerate with credentials (CME)",
    description: "Use NetExec with valid credentials",
    command: "nxc smb $target_ip -u 'username' -p 'password' --shares",
    order: 21,
  },
  {
    id: "smb-auth-3",
    serviceType: "smb",
    category: "authenticated",
    title: "Check for PSExec execution",
    description: "Test if remote execution is possible",
    command: "nxc smb $target_ip -u 'username' -p 'password' -x 'whoami'",
    order: 22,
  },

  // HTTP Enumeration
  {
    id: "http-enum-1",
    serviceType: "http",
    category: "enumeration",
    title: "Run Nikto scan",
    description: "Web vulnerability scanner",
    command: "nikto -h http://$target_ip:$port",
    order: 1,
  },
  {
    id: "http-enum-2",
    serviceType: "http",
    category: "enumeration",
    title: "Directory brute force with Gobuster",
    description: "Enumerate directories and files",
    command: "gobuster dir -u http://$target_ip:$port -w /usr/share/wordlists/dirb/common.txt",
    order: 2,
  },
  {
    id: "http-enum-3",
    serviceType: "http",
    category: "enumeration",
    title: "Enumerate subdomains with ffuf",
    description: "Virtual host/subdomain enumeration",
    command: "ffuf -u http://$target_ip -H 'Host: FUZZ.target.com' -w /usr/share/seclists/Discovery/DNS/subdomains-top1million-5000.txt",
    order: 3,
  },
  {
    id: "http-enum-4",
    serviceType: "http",
    category: "enumeration",
    title: "Check robots.txt",
    description: "Look for hidden paths in robots.txt",
    command: "curl http://$target_ip:$port/robots.txt",
    order: 4,
  },
  {
    id: "http-enum-5",
    serviceType: "http",
    category: "enumeration",
    title: "Identify technologies with whatweb",
    description: "Fingerprint web technologies",
    command: "whatweb http://$target_ip:$port",
    order: 5,
  },
  {
    id: "http-unauth-1",
    serviceType: "http",
    category: "unauthenticated",
    title: "Test for SQL injection",
    description: "Use sqlmap for SQL injection testing",
    command: "sqlmap -u 'http://$target_ip:$port/page?id=1' --batch",
    order: 10,
  },
  {
    id: "http-unauth-2",
    serviceType: "http",
    category: "unauthenticated",
    title: "Check for default credentials",
    description: "Test common default login credentials",
    command: "hydra -L /usr/share/seclists/Usernames/top-usernames-shortlist.txt -P /usr/share/seclists/Passwords/Common-Credentials/top-20-common-SSH-passwords.txt $target_ip http-post-form '/login:username=^USER^&password=^PASS^:Invalid'",
    order: 11,
  },
  {
    id: "http-unauth-3",
    serviceType: "http",
    category: "unauthenticated",
    title: "Test for LFI/RFI",
    description: "Check for file inclusion vulnerabilities",
    command: "ffuf -u 'http://$target_ip:$port/page?file=FUZZ' -w /usr/share/seclists/Fuzzing/LFI/LFI-Jhaddix.txt",
    order: 12,
  },
  {
    id: "http-auth-1",
    serviceType: "http",
    category: "authenticated",
    title: "Enumerate authenticated pages",
    description: "Access protected areas with valid session",
    command: "curl -b 'session=COOKIE' http://$target_ip:$port/admin",
    order: 20,
  },

  // SSH Enumeration
  {
    id: "ssh-enum-1",
    serviceType: "ssh",
    category: "enumeration",
    title: "Banner grab",
    description: "Get SSH version and banner",
    command: "nmap -sV -p$port $target_ip --script ssh2-enum-algos",
    order: 1,
  },
  {
    id: "ssh-enum-2",
    serviceType: "ssh",
    category: "enumeration",
    title: "Check for username enumeration",
    description: "Test if SSH allows username enumeration (CVE-2018-15473)",
    command: "python3 ssh-username-enum.py $target_ip -w usernames.txt",
    links: ["https://github.com/epi052/cve-2018-15473"],
    order: 2,
  },
  {
    id: "ssh-unauth-1",
    serviceType: "ssh",
    category: "unauthenticated",
    title: "Brute force with Hydra",
    description: "Password brute force attack",
    command: "hydra -l admin -P /usr/share/wordlists/rockyou.txt ssh://$target_ip:$port",
    order: 10,
  },
  {
    id: "ssh-auth-1",
    serviceType: "ssh",
    category: "authenticated",
    title: "Connect with credentials",
    description: "SSH login with valid credentials",
    command: "ssh username@$target_ip -p $port",
    order: 20,
  },
  {
    id: "ssh-auth-2",
    serviceType: "ssh",
    category: "authenticated",
    title: "Check sudo privileges",
    description: "Enumerate sudo permissions",
    command: "sudo -l",
    order: 21,
  },

  // FTP Enumeration
  {
    id: "ftp-enum-1",
    serviceType: "ftp",
    category: "enumeration",
    title: "Banner grab",
    description: "Get FTP version and banner",
    command: "nmap -sV -p$port --script ftp-anon $target_ip",
    order: 1,
  },
  {
    id: "ftp-enum-2",
    serviceType: "ftp",
    category: "enumeration",
    title: "Check anonymous access",
    description: "Test for anonymous FTP login",
    command: "ftp $target_ip\n# Try: anonymous / anonymous",
    order: 2,
  },
  {
    id: "ftp-unauth-1",
    serviceType: "ftp",
    category: "unauthenticated",
    title: "Brute force with Hydra",
    description: "Password brute force attack",
    command: "hydra -l admin -P /usr/share/wordlists/rockyou.txt ftp://$target_ip:$port",
    order: 10,
  },
  {
    id: "ftp-auth-1",
    serviceType: "ftp",
    category: "authenticated",
    title: "Download all files recursively",
    description: "Mirror the FTP server contents",
    command: "wget -r ftp://username:password@$target_ip",
    order: 20,
  },

  // RDP Enumeration
  {
    id: "rdp-enum-1",
    serviceType: "rdp",
    category: "enumeration",
    title: "Check RDP encryption",
    description: "Enumerate RDP security settings",
    command: "nmap --script rdp-enum-encryption -p$port $target_ip",
    order: 1,
  },
  {
    id: "rdp-unauth-1",
    serviceType: "rdp",
    category: "unauthenticated",
    title: "Check for BlueKeep (CVE-2019-0708)",
    description: "Scan for BlueKeep vulnerability",
    command: "nmap --script rdp-vuln-ms12-020 -p$port $target_ip",
    links: ["https://www.rapid7.com/db/modules/exploit/windows/rdp/cve_2019_0708_bluekeep_rce"],
    order: 10,
  },
  {
    id: "rdp-unauth-2",
    serviceType: "rdp",
    category: "unauthenticated",
    title: "Brute force with Hydra",
    description: "Password brute force attack",
    command: "hydra -l administrator -P /usr/share/wordlists/rockyou.txt rdp://$target_ip",
    order: 11,
  },
  {
    id: "rdp-auth-1",
    serviceType: "rdp",
    category: "authenticated",
    title: "Connect with xfreerdp",
    description: "RDP connection with valid credentials",
    command: "xfreerdp /u:username /p:password /v:$target_ip:$port",
    order: 20,
  },

  // MySQL Enumeration
  {
    id: "mysql-enum-1",
    serviceType: "mysql",
    category: "enumeration",
    title: "Banner grab and version",
    description: "Get MySQL version",
    command: "nmap -sV -p$port --script mysql-info $target_ip",
    order: 1,
  },
  {
    id: "mysql-unauth-1",
    serviceType: "mysql",
    category: "unauthenticated",
    title: "Check for empty password",
    description: "Test root with no password",
    command: "mysql -h $target_ip -u root",
    order: 10,
  },
  {
    id: "mysql-unauth-2",
    serviceType: "mysql",
    category: "unauthenticated",
    title: "Brute force with Hydra",
    description: "Password brute force attack",
    command: "hydra -l root -P /usr/share/wordlists/rockyou.txt mysql://$target_ip",
    order: 11,
  },
  {
    id: "mysql-auth-1",
    serviceType: "mysql",
    category: "authenticated",
    title: "Dump databases",
    description: "List all databases",
    command: "mysql -h $target_ip -u username -p -e 'SHOW DATABASES;'",
    order: 20,
  },

  // LDAP Enumeration
  {
    id: "ldap-enum-1",
    serviceType: "ldap",
    category: "enumeration",
    title: "Anonymous bind enumeration",
    description: "Enumerate LDAP with anonymous bind",
    command: "ldapsearch -x -H ldap://$target_ip -b 'dc=domain,dc=local'",
    order: 1,
  },
  {
    id: "ldap-enum-2",
    serviceType: "ldap",
    category: "enumeration",
    title: "Get base DN",
    description: "Discover the base distinguished name",
    command: "nmap -p$port --script ldap-rootdse $target_ip",
    order: 2,
  },
  {
    id: "ldap-auth-1",
    serviceType: "ldap",
    category: "authenticated",
    title: "Enumerate users with credentials",
    description: "List all domain users",
    command: "ldapsearch -x -H ldap://$target_ip -D 'cn=admin,dc=domain,dc=local' -w password -b 'dc=domain,dc=local' '(objectClass=user)'",
    order: 20,
  },

  // Kerberos Enumeration
  {
    id: "kerberos-enum-1",
    serviceType: "kerberos",
    category: "enumeration",
    title: "Enumerate users with kerbrute",
    description: "Validate usernames against Kerberos",
    command: "kerbrute userenum -d domain.local --dc $target_ip usernames.txt",
    order: 1,
  },
  {
    id: "kerberos-unauth-1",
    serviceType: "kerberos",
    category: "unauthenticated",
    title: "AS-REP Roasting",
    description: "Request TGTs for users without preauth",
    command: "GetNPUsers.py domain.local/ -usersfile users.txt -no-pass -dc-ip $target_ip",
    order: 10,
  },
  {
    id: "kerberos-auth-1",
    serviceType: "kerberos",
    category: "authenticated",
    title: "Kerberoasting",
    description: "Request service tickets for offline cracking",
    command: "GetUserSPNs.py domain.local/username:password -dc-ip $target_ip -request",
    order: 20,
  },

  // SNMP Enumeration
  {
    id: "snmp-enum-1",
    serviceType: "snmp",
    category: "enumeration",
    title: "SNMP walk with default community",
    description: "Enumerate SNMP with public community string",
    command: "snmpwalk -v2c -c public $target_ip",
    order: 1,
  },
  {
    id: "snmp-enum-2",
    serviceType: "snmp",
    category: "enumeration",
    title: "Brute force community strings",
    description: "Test common community strings",
    command: "onesixtyone -c /usr/share/seclists/Discovery/SNMP/common-snmp-community-strings.txt $target_ip",
    order: 2,
  },

  // DNS Enumeration
  {
    id: "dns-enum-1",
    serviceType: "dns",
    category: "enumeration",
    title: "Zone transfer attempt",
    description: "Try AXFR zone transfer",
    command: "dig axfr @$target_ip domain.local",
    order: 1,
  },
  {
    id: "dns-enum-2",
    serviceType: "dns",
    category: "enumeration",
    title: "Enumerate subdomains",
    description: "DNS subdomain enumeration",
    command: "dnsrecon -d domain.local -n $target_ip -t std",
    order: 2,
  },

  // NFS Enumeration  
  {
    id: "nfs-enum-1",
    serviceType: "nfs",
    category: "enumeration",
    title: "List NFS shares",
    description: "Show available NFS exports",
    command: "showmount -e $target_ip",
    order: 1,
  },
  {
    id: "nfs-auth-1",
    serviceType: "nfs",
    category: "authenticated",
    title: "Mount NFS share",
    description: "Mount an NFS export",
    command: "mount -t nfs $target_ip:/share /mnt/nfs",
    order: 20,
  },

  // WinRM Enumeration
  {
    id: "winrm-enum-1",
    serviceType: "winrm",
    category: "enumeration",
    title: "Check WinRM access",
    description: "Test if WinRM is accessible",
    command: "NetExec winrm $target_ip",
    order: 1,
  },
  {
    id: "winrm-auth-1",
    serviceType: "winrm",
    category: "authenticated",
    title: "Connect with evil-winrm",
    description: "Get shell via WinRM",
    command: "evil-winrm -i $target_ip -u username -p password",
    order: 20,
  },
];

export function getChecklistItemsForServiceType(serviceType: string): ChecklistItem[] {
  return defaultChecklistItems.filter((item) => item.serviceType === serviceType);
}
